# Generated by Django 4.0.5 on 2022-07-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='email',
            field=models.EmailField(default=False, max_length=254),
            preserve_default=False,
        ),
    ]
