# Generated by Django 4.0.5 on 2022-07-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
